let questions = [
    {
        "question": "Was besagt das Heisenberg'sche Unschärferelations-Prinzip?",
        "answer_1": "Die Geschwindigkeit eines Teilchens kann niemals genau bestimmt werden.",
        "answer_2": "Es ist unmöglich, gleichzeitig Ort und Impuls eines Teilchens genau zu messen.",
        "answer_3": "Energie kann weder erzeugt noch vernichtet, sondern nur umgewandelt werden.",
        "answer_4": "Jedes Teilchen verhält sich sowohl als Welle als auch als Teilchen.",
        "right_answer": 2,
    },
    {
        "question": "Die sogenannte Quantenhypothese des Bewusstseins legt nahe, dass:",
        "answer_1": "Quantenphänomene eine entscheidende Rolle bei der Entstehung von Bewusstsein spielen.",
        "answer_2": "Das Universum ein riesiger Quantencomputer ist.",
        "answer_3": "Bewusstsein zeitlich rückwärts wirken kann.",
        "answer_4": "Quantenverschränkung die Grundlage für telepathische Kommunikation ist.",
        "right_answer": 1,
    },
    {
        "question": "Was ist Zeit eigentlich?",
        "answer_1": "Eine objektive Größe, die für alle gleichmäßig vergeht.",
        "answer_2": "Eine menschliche Konstruktion aus der dritten Dimension, um Ereignisse zu ordnen.",
        "answer_3": "tEine Dimension des Raums, die sich von den anderen unterscheidet.",
        "answer_4": "Eine Illusion, die durch die Veränderung von Zuständen entsteht.",
        "right_answer": 2,
    },
    {
        "question": "Was ist Quantenverschränkung?",
        "answer_1": "Ein Zustand, in dem zwei Teilchen, unabhängig von der Entfernung, miteinander verbunden sind.",
        "answer_2": "Ein Prozess, bei dem ein Teilchen in mehrere kleinere Teilchen zerfällt.",
        "answer_3": "Die Fähigkeit eines Teilchens, gleichzeitig an mehreren Orten zu existieren.",
        "answer_4": "Die Wechselwirkung von Lichtteilchen mit Materie.",
        "right_answer": 1,
    },
    {
        "question": "Was ist der grundlegende Unterschied zwischen Bewusstsein und Intelligenz?",
        "answer_1": "Intelligenz bezieht sich auf die Fähigkeit, Probleme zu lösen und Wissen anzuwenden, während Bewusstsein die subjektive Erfahrung von sich selbst und der Welt ist.",
        "answer_2": "Bewusstsein ist eine Voraussetzung für Intelligenz, da man ohne Bewusstsein nicht denken oder lernen kann.",
        "answer_3": "Intelligenz ist eine Form von Bewusstsein, die sich auf kognitive Fähigkeiten konzentriert.",
        "answer_4": "Es gibt keinen fundamentalen Unterschied, da beide Begriffe synonym verwendet werden können.",
        "right_answer": 1,
    },
    {
        "question": "Wie entsteht ein Schwarzes Loch?",
        "answer_1": "Wenn ein Stern am Ende seines Lebenszyklus explodiert und sein Kern unter seiner eigenen Schwerkraft kollabiert.",
        "answer_2": "Durch die Kollision zweier Neutronensterne.",
        "answer_3": "Wenn genügend Materie in einem bestimmten Raum konzentriert wird, sodass die Gravitationskraft so stark wird, dass nichts, nicht einmal Licht, entweichen kann.",
        "answer_4": "Alle oben genannten Antworten sind korrekt.",
        "right_answer": 4,
    },
]